run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gocritic
    - gosec
    - unconvert
    - prealloc
    - exportloopref
    - goconst
    - gocognit
    - gocyclo
    - dupl
    - funlen
    - lll
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - sqlclosecheck
    - thelper
    - tparallel
    - typecheck
    - varcheck
    - whitespace
    - wrapcheck
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - godot
    - godox
    - goerr113
    - gomnd
    - gomodguard
    - goprintffuncname
    - gosec
    - interfacer
    - makezero
    - maligned
    - noctx
    - nolintlint
    - promlinter
    - rowserrcheck
    - scopelint
    - tagliatelle
    - testpackage
    - unconvert
    - unparam
    - wastedassign
    - whitespace

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  govet:
    check-shadowing: true
  lll:
    line-length: 140
  maligned:
    suggest-new: true
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false
  revive:
    min-confidence: 0
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: unexported-return
        severity: warning
        disabled: false
      - name: error-return
        severity: warning
        disabled: false
      - name: error-naming
        severity: warning
        disabled: false
      - name: error-strings
        severity: warning
        disabled: false
      - name: receiver-naming
        severity: warning
        disabled: false
      - name: increment-decrement
        severity: warning
        disabled: false
      - name: var-naming
        severity: warning
        disabled: false
      - name: range
        severity: warning
        disabled: false
      - name: increment-decrement
        severity: warning
        disabled: false
      - name: var-declaration
        severity: warning
        disabled: false
      - name: range
        severity: warning
        disabled: false
      - name: range
        severity: warning
        disabled: false
      - name: range
        severity: warning
        disabled: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - funlen
        - gocritic
    - path: internal/service/checker\.go
      linters:
        - gocritic
  max-issues-per-linter: 0
  max-same-issues: 0

